version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./:/go/src/kotatuneko-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
