version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./:/go/src/kotatuneko-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  db:
    platform: linux/x86_64
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - kotatuneko-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s

  redis:
    image: "redis:latest"
    container_name: kotatuneko-redis
    ports:
      - "6379:${REDIS_PORT:-6379}"
    networks:
      - container-link
    restart: always
    volumes:
      - kotatuneko-redis-volume:/data:rw
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  container-link:
    name: kotatuneko.network

volumes:
  kotatuneko-redis-volume:
    name: kotatuneko-redis
    driver: local
  kotatuneko-db-volume:
    name: kotatuneko-db
    driver: local
