// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/K-Kizuku/kotatuneko-backend/internal/app/application/service"
	"github.com/K-Kizuku/kotatuneko-backend/internal/app/infrastructure"
	"github.com/K-Kizuku/kotatuneko-backend/internal/app/presentation"
	"github.com/K-Kizuku/kotatuneko-backend/internal/app/presentation/handler"
	"github.com/K-Kizuku/kotatuneko-backend/internal/app/presentation/switcher"
	"github.com/K-Kizuku/kotatuneko-backend/internal/app/presentation/websocket"
	"github.com/K-Kizuku/kotatuneko-backend/pkg/cache"
)

// Injectors from wire.go:

func InitHandler() *presentation.Root {
	client := cache.NewCacheClient()
	iRoomObjectRepository := infrastructure.NewRoomObjectRepository(client)
	iRoomObjectService := service.NewRoomObjectService(iRoomObjectRepository)
	iMessageSender := infrastructure.NewMsgSender()
	iSwitcher := switcher.NewPhysicsSwitcher(iRoomObjectService)
	iwsHandler := websocket.NewWSHandler(iMessageSender, iSwitcher)
	physicsHandler := handler.NewPhysicsHandler(iRoomObjectService, iwsHandler, iSwitcher)
	root := presentation.New(physicsHandler)
	return root
}
