name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go 1.23rc1
        run: |
          wget https://golang.org/dl/go1.23rc1.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.23rc1.linux-amd64.tar.gz
          echo "export PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
      - name: Setup Go environment
        run: echo "GOROOT=$(go env GOROOT)" >> $GITHUB_ENV
      - name: Install dependencies
        run: go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
